spring:
  datasource:
    url: jdbc:mysql://localhost:3307/currency_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
