spring:
  application:
    name: currency-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:currencydb}
    username: ${DB_USER:user}
    password: ${DB_PASS:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}			

server:
  port: 8080
